//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accounts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts is a basic personal financial-accounting software.
        ///
        ///https://github.com/GaelGirodon/accounts.
        /// </summary>
        public static string About_Content {
            get {
                return ResourceManager.GetString("About_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, unable to create a backup of the account file..
        /// </summary>
        public static string Account_Archive_Error {
            get {
                return ResourceManager.GetString("Account_Archive_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully backed up to {0}..
        /// </summary>
        public static string Account_Archive_Success {
            get {
                return ResourceManager.GetString("Account_Archive_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive account.
        /// </summary>
        public static string Account_Archive_Title {
            get {
                return ResourceManager.GetString("Account_Archive_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyAccount.
        /// </summary>
        public static string Account_DefaultFileName {
            get {
                return ResourceManager.GetString("Account_DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account file.
        /// </summary>
        public static string Account_FileType {
            get {
                return ResourceManager.GetString("Account_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an account file.
        /// </summary>
        public static string Account_Open_Dialog_Title {
            get {
                return ResourceManager.GetString("Account_Open_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is not a valid account file..
        /// </summary>
        public static string Account_Open_InvalidFile {
            get {
                return ResourceManager.GetString("Account_Open_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the account before exit?.
        /// </summary>
        public static string Account_Save_BeforeExit_Content {
            get {
                return ResourceManager.GetString("Account_Save_BeforeExit_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the account.
        /// </summary>
        public static string Account_Save_BeforeExit_Title {
            get {
                return ResourceManager.GetString("Account_Save_BeforeExit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the account file.
        /// </summary>
        public static string Account_Save_Dialog_Title {
            get {
                return ResourceManager.GetString("Account_Save_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, unable to save the account file to the selected location..
        /// </summary>
        public static string Account_Save_Error {
            get {
                return ResourceManager.GetString("Account_Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully saved to {0}..
        /// </summary>
        public static string Account_Save_Success {
            get {
                return ResourceManager.GetString("Account_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Home_New {
            get {
                return ResourceManager.GetString("Home_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account (Ctrl+N).
        /// </summary>
        public static string Home_New_Description {
            get {
                return ResourceManager.GetString("Home_New_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string Home_Open {
            get {
                return ResourceManager.GetString("Home_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an account file (Ctrl+O).
        /// </summary>
        public static string Home_Open_Description {
            get {
                return ResourceManager.GetString("Home_Open_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Menu_Edit_Copy {
            get {
                return ResourceManager.GetString("Menu_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Menu_Edit_Cut {
            get {
                return ResourceManager.GetString("Menu_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Duplicate....
        /// </summary>
        public static string Menu_Edit_Duplicate {
            get {
                return ResourceManager.GetString("Menu_Edit_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate selected transactions.
        /// </summary>
        public static string Menu_Edit_Duplicate_Description {
            get {
                return ResourceManager.GetString("Menu_Edit_Duplicate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Menu_Edit_Paste {
            get {
                return ResourceManager.GetString("Menu_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_rchive.
        /// </summary>
        public static string Menu_File_Archive {
            get {
                return ResourceManager.GetString("Menu_File_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a backup of the account file.
        /// </summary>
        public static string Menu_File_Archive_Description {
            get {
                return ResourceManager.GetString("Menu_File_Archive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the current month (Ctrl+M).
        /// </summary>
        public static string Navigation_Current {
            get {
                return ResourceManager.GetString("Navigation_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next month (Ctrl+Tab).
        /// </summary>
        public static string Navigation_Month_Next {
            get {
                return ResourceManager.GetString("Navigation_Month_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month (Ctrl+Shift+Tab).
        /// </summary>
        public static string Navigation_Month_Previous {
            get {
                return ResourceManager.GetString("Navigation_Month_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next year.
        /// </summary>
        public static string Navigation_Year_Next {
            get {
                return ResourceManager.GetString("Navigation_Year_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous year.
        /// </summary>
        public static string Navigation_Year_Previous {
            get {
                return ResourceManager.GetString("Navigation_Year_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Transaction_Amount {
            get {
                return ResourceManager.GetString("Transaction_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string Transaction_Checked {
            get {
                return ResourceManager.GetString("Transaction_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check off.
        /// </summary>
        public static string Transaction_CheckOff {
            get {
                return ResourceManager.GetString("Transaction_CheckOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Transaction_Date {
            get {
                return ResourceManager.GetString("Transaction_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Transaction_Form_Add {
            get {
                return ResourceManager.GetString("Transaction_Form_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a transaction (Ctrl+T).
        /// </summary>
        public static string Transaction_Form_Add_Description {
            get {
                return ResourceManager.GetString("Transaction_Form_Add_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Transaction_Form_Cancel {
            get {
                return ResourceManager.GetString("Transaction_Form_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel modifications.
        /// </summary>
        public static string Transaction_Form_Cancel_Description {
            get {
                return ResourceManager.GetString("Transaction_Form_Cancel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Transaction_Form_Delete {
            get {
                return ResourceManager.GetString("Transaction_Form_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a transaction cannot be undone, are you sure you want to proceed?.
        /// </summary>
        public static string Transaction_Form_Delete_Confirmation {
            get {
                return ResourceManager.GetString("Transaction_Form_Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete transaction.
        /// </summary>
        public static string Transaction_Form_Delete_Description {
            get {
                return ResourceManager.GetString("Transaction_Form_Delete_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Transaction_Form_Save {
            get {
                return ResourceManager.GetString("Transaction_Form_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save modifications.
        /// </summary>
        public static string Transaction_Form_Save_Description {
            get {
                return ResourceManager.GetString("Transaction_Form_Save_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction amount is invalid..
        /// </summary>
        public static string Transaction_Form_Save_Validation_InvalidAmount {
            get {
                return ResourceManager.GetString("Transaction_Form_Save_Validation_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction method is required..
        /// </summary>
        public static string Transaction_Form_Save_Validation_MethodRequired {
            get {
                return ResourceManager.GetString("Transaction_Form_Save_Validation_MethodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction name is required..
        /// </summary>
        public static string Transaction_Form_Save_Validation_NameRequired {
            get {
                return ResourceManager.GetString("Transaction_Form_Save_Validation_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Transaction_Method {
            get {
                return ResourceManager.GetString("Transaction_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Transaction_Method_Card {
            get {
                return ResourceManager.GetString("Transaction_Method_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Transaction_Method_Cash {
            get {
                return ResourceManager.GetString("Transaction_Method_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque.
        /// </summary>
        public static string Transaction_Method_Cheque {
            get {
                return ResourceManager.GetString("Transaction_Method_Cheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transaction_Method_Transfer {
            get {
                return ResourceManager.GetString("Transaction_Method_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Transaction_Name {
            get {
                return ResourceManager.GetString("Transaction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New transaction.
        /// </summary>
        public static string Transaction_Name_DefaultValue {
            get {
                return ResourceManager.GetString("Transaction_Name_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        public static string Transactions_Balance {
            get {
                return ResourceManager.GetString("Transactions_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account balance at the end of the month.
        /// </summary>
        public static string Transactions_Balance_Description {
            get {
                return ResourceManager.GetString("Transactions_Balance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit:.
        /// </summary>
        public static string Transactions_Credit {
            get {
                return ResourceManager.GetString("Transactions_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month credits sum.
        /// </summary>
        public static string Transactions_Credit_Description {
            get {
                return ResourceManager.GetString("Transactions_Credit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit:.
        /// </summary>
        public static string Transactions_Debit {
            get {
                return ResourceManager.GetString("Transactions_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month debits sum.
        /// </summary>
        public static string Transactions_Debit_Description {
            get {
                return ResourceManager.GetString("Transactions_Debit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Transactions_Duplicate_Dialog_Cancel {
            get {
                return ResourceManager.GetString("Transactions_Duplicate_Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate selected transactions to:.
        /// </summary>
        public static string Transactions_Duplicate_Dialog_Header {
            get {
                return ResourceManager.GetString("Transactions_Duplicate_Dialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Transactions_Duplicate_Dialog_Submit {
            get {
                return ResourceManager.GetString("Transactions_Duplicate_Dialog_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate transactions.
        /// </summary>
        public static string Transactions_Duplicate_Dialog_Title {
            get {
                return ResourceManager.GetString("Transactions_Duplicate_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected transactions have been successfully duplicated to {0}..
        /// </summary>
        public static string Transactions_Duplicate_Success {
            get {
                return ResourceManager.GetString("Transactions_Duplicate_Success", resourceCulture);
            }
        }
    }
}
